### ISSUE TITLE
Does text on brochure site focus too heavily on "science" to potential exclusion of other disciplines?

### ISSUE THREAD

**Issue by colliand** [2i2c-org/2i2c-org.github.io#10]
The tag line `infrastructure for interactive computing in science and education` on the brochure site made me wonder if researchers working in digital humanities or social sciences might conclude that 2i2c is not built for them?

**Comment by choldgraf** [comment]
Agree - we should make it "research" not "science" at the very least

**Comment by choldgraf** [comment]
I think that we have improved this language a bit, so it is less "science"-focused 👍
