### ISSUE TITLE
Publish 'right to fork' principles odcument

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/2i2c-org.github.io#23]
Customer freedom and 'right to fork' are important aspects that differentiate 2i2c from the competition. I think we should clean it up, gather agreement, and publish it on the website before sending out our introductory blog post (#22).

Link to draft here: https://docs.google.com/document/d/1A2lEjvmZuhmNpPc1qBnT4QLFmKza7p8Io9w36UHCIT0/edit?usp=drive_web&ouid=101500906458831444600

Tasks:
- [x] Edit to be publishable
- [x] Make a PR here, as a document folks can comment on
- [x] Discuss with 2i2c founders to make sure there are no major objections
- [x] Decide on an appropriate title
- [x] PUBLISH!

**Comment by yuvipanda** [comment]
The tone of the document should balance rhetoric from the Free Software movement, the free culture movement, and the open science movement. Lots of overlap, but definitely differences there in terms of terminology.

**Comment by choldgraf** [comment]
published in #22
